# packages in environment at C:\Users\hyunw\miniforge3\envs\ksbcw:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       2_gnu    conda-forge
anyio                     4.9.0              pyh29332c3_0    conda-forge
argon2-cffi               25.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py313ha7868ed_5    conda-forge
arrow                     1.3.0              pyhd8ed1ab_1    conda-forge
asttokens                 3.0.0              pyhd8ed1ab_1    conda-forge
async-lru                 2.0.5              pyh29332c3_0    conda-forge
attrs                     25.3.0             pyh71513ae_0    conda-forge
babel                     2.17.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.13.4             pyha770c72_0    conda-forge
bleach                    6.2.0              pyh29332c3_4    conda-forge
bleach-with-css           6.2.0                h82add2a_4    conda-forge
brotli                    1.1.0                h2466b09_3    conda-forge
brotli-bin                1.1.0                h2466b09_3    conda-forge
brotli-python             1.1.0           py313h5813708_3    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2025.4.26            h4c7d964_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.4               h5782bbf_0    conda-forge
certifi                   2025.4.26          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py313ha7868ed_0    conda-forge
charset-normalizer        3.4.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
comm                      0.2.2              pyhd8ed1ab_1    conda-forge
contourpy                 1.3.2           py313h1ec8472_0    conda-forge
cpython                   3.13.5          py313hd8ed1ab_101    conda-forge
cycler                    0.12.1             pyhd8ed1ab_1    conda-forge
debugpy                   1.8.14          py313h5813708_0    conda-forge
decorator                 5.2.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
double-conversion         3.3.1                he0c23c2_0    conda-forge
exceptiongroup            1.3.0              pyhd8ed1ab_0    conda-forge
executing                 2.2.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h765892d_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.58.2          py313hb4c8b1a_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_1    conda-forge
freetype                  2.13.3               h57928b3_1    conda-forge
graphite2                 1.3.13            h63175ca_1003    conda-forge
h11                       0.16.0             pyhd8ed1ab_0    conda-forge
h2                        4.2.0              pyhd8ed1ab_0    conda-forge
harfbuzz                  11.2.1               h8796e6f_0    conda-forge
hpack                     4.1.0              pyhd8ed1ab_0    conda-forge
httpcore                  1.0.9              pyh29332c3_0    conda-forge
httpx                     0.28.1             pyhd8ed1ab_0    conda-forge
hyperframe                6.1.0              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he0c23c2_0    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
importlib-metadata        8.7.0              pyhe01879c_1    conda-forge
importlib_resources       6.5.2              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
ipykernel                 6.29.5             pyh4bbf305_0    conda-forge
ipython                   9.3.0              pyh6be1c34_0    conda-forge
ipython_pygments_lexers   1.1.1              pyhd8ed1ab_0    conda-forge
ipywidgets                8.1.7              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_1    conda-forge
jedi                      0.19.2             pyhd8ed1ab_1    conda-forge
jinja2                    3.1.6              pyhd8ed1ab_0    conda-forge
json5                     0.12.0             pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py313hfa70ccb_1    conda-forge
jsonschema                4.24.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2025.4.1           pyh29332c3_0    conda-forge
jsonschema-with-format-nongpl 4.24.0               hd8ed1ab_0    conda-forge
jupyter                   1.1.1              pyhd8ed1ab_1    conda-forge
jupyter-lsp               2.2.5              pyhe01879c_2    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_1    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_1    conda-forge
jupyter_core              5.8.1              pyh5737063_0    conda-forge
jupyter_events            0.12.0             pyh29332c3_0    conda-forge
jupyter_server            2.16.0             pyhe01879c_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_1    conda-forge
jupyterlab                4.4.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_2    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_1    conda-forge
jupyterlab_widgets        3.0.15             pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.7           py313h1ec8472_0    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.17                 hbcf6048_0    conda-forge
lerc                      4.0.0                h6470a55_1    conda-forge
libblas                   3.9.0           31_h641d27c_mkl    conda-forge
libbrotlicommon           1.1.0                h2466b09_3    conda-forge
libbrotlidec              1.1.0                h2466b09_3    conda-forge
libbrotlienc              1.1.0                h2466b09_3    conda-forge
libcblas                  3.9.0           31_h5e41251_mkl    conda-forge
libclang13                20.1.6          default_h6e92b77_0    conda-forge
libdeflate                1.24                 h76ddb4d_0    conda-forge
libexpat                  2.7.0                he0c23c2_0    conda-forge
libffi                    3.4.6                h537db12_1    conda-forge
libfreetype               2.13.3               h57928b3_1    conda-forge
libfreetype6              2.13.3               h0b5ce68_1    conda-forge
libgcc                    15.1.0               h1383e82_2    conda-forge
libglib                   2.84.2               hbc94333_0    conda-forge
libgomp                   15.1.0               h1383e82_2    conda-forge
libhwloc                  2.11.2          default_ha69328c_1001    conda-forge
libiconv                  1.18                 h135ad9c_1    conda-forge
libintl                   0.22.5               h5728263_3    conda-forge
libjpeg-turbo             3.1.0                h2466b09_0    conda-forge
liblapack                 3.9.0           31_h1aa476e_mkl    conda-forge
liblzma                   5.8.1                h2466b09_2    conda-forge
libmpdec                  4.0.0                h2466b09_0    conda-forge
libpng                    1.6.47               h7a4582a_0    conda-forge
libsodium                 1.0.20               hc70643c_0    conda-forge
libsqlite                 3.50.1               h67fdade_0    conda-forge
libtiff                   4.7.0                h05922d8_5    conda-forge
libwebp-base              1.5.0                h3b0e114_0    conda-forge
libwinpthread             12.0.0.r4.gg4f2fc60ca      h57928b3_9    conda-forge
libxcb                    1.17.0               h0e4246c_0    conda-forge
libxml2                   2.13.8               h442d1da_0    conda-forge
libxslt                   1.1.39               h3df6e99_0    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
markupsafe                3.0.2           py313hb4c8b1a_1    conda-forge
matplotlib                3.10.3          py313hfa70ccb_0    conda-forge
matplotlib-base           3.10.3          py313h81b4f16_0    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_1    conda-forge
mistune                   3.1.3              pyh29332c3_0    conda-forge
mkl                       2024.2.2            h66d3029_15    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.10.2             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.6             pyh29332c3_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_1    conda-forge
notebook                  7.4.3              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_1    conda-forge
numpy                     2.3.0           py313hefb8edb_0    conda-forge
openjpeg                  2.5.3                h4d64b90_0    conda-forge
openssl                   3.5.0                ha4e3fda_1    conda-forge
overrides                 7.7.0              pyhd8ed1ab_1    conda-forge
packaging                 25.0               pyh29332c3_1    conda-forge
pandas                    2.3.0           py313hf91d08e_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_1    conda-forge
pcre2                     10.45                h99c9b8b_0    conda-forge
pickleshare               0.7.5           pyhd8ed1ab_1004    conda-forge
pillow                    11.2.1          py313hda88b71_0    conda-forge
pip                       25.1.1             pyh145f28c_0    conda-forge
pixman                    0.46.2               had0cd8c_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_2    conda-forge
platformdirs              4.3.8              pyhe01879c_0    conda-forge
prometheus_client         0.22.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.51             pyha770c72_0    conda-forge
prompt_toolkit            3.0.51               hd8ed1ab_0    conda-forge
psutil                    7.0.0           py313ha7868ed_0    conda-forge
pthread-stubs             0.4               h0e40799_1002    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_1    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pygments                  2.19.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.2.3              pyhd8ed1ab_1    conda-forge
pyside6                   6.9.1           py313hd8d090c_0    conda-forge
pysocks                   1.7.1              pyh09c184e_7    conda-forge
python                    3.13.5          h261c0b1_101_cp313    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_1    conda-forge
python-fastjsonschema     2.21.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2025.2             pyhd8ed1ab_0    conda-forge
python_abi                3.13                    7_cp313    conda-forge
pytz                      2025.2             pyhd8ed1ab_0    conda-forge
pywin32                   307             py313h5813708_3    conda-forge
pywinpty                  2.0.15          py313h5813708_0    conda-forge
pyyaml                    6.0.2           py313hb4c8b1a_2    conda-forge
pyzmq                     26.4.0          py313h2100fd5_0    conda-forge
qhull                     2020.2               hc790b64_5    conda-forge
qt6-main                  6.9.1                h02ddd7d_0    conda-forge
referencing               0.36.2             pyh29332c3_0    conda-forge
requests                  2.32.4             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_1    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.25.1          py313ha8a9a3c_0    conda-forge
scipy                     1.15.2          py313h2eca4b9_0    conda-forge
send2trash                1.8.3              pyh5737063_1    conda-forge
setuptools                80.9.0             pyhff2d567_0    conda-forge
six                       1.17.0             pyhd8ed1ab_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_1    conda-forge
soupsieve                 2.7                pyhd8ed1ab_0    conda-forge
stack_data                0.6.3              pyhd8ed1ab_1    conda-forge
tbb                       2021.13.0            h62715c5_1    conda-forge
terminado                 0.18.1             pyh5737063_0    conda-forge
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h2c6b04d_2    conda-forge
tomli                     2.2.1              pyhd8ed1ab_1    conda-forge
tornado                   6.5.1           py313ha7868ed_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_1    conda-forge
types-python-dateutil     2.9.0.20250516     pyhd8ed1ab_0    conda-forge
typing-extensions         4.14.0               h32cad80_0    conda-forge
typing_extensions         4.14.0             pyhe01879c_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_1    conda-forge
tzdata                    2025b                h78e105d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
uri-template              1.3.0              pyhd8ed1ab_1    conda-forge
urllib3                   2.4.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                h2b53caa_26    conda-forge
vc14_runtime              14.42.34438         hfd919c2_26    conda-forge
vs2015_runtime            14.42.34438         h7142326_26    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_1    conda-forge
webcolors                 24.11.1            pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_3    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_1    conda-forge
widgetsnbextension        4.0.14             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyh7428d3b_8    conda-forge
winpty                    0.4.3                         4    conda-forge
xorg-libxau               1.0.12               h0e40799_0    conda-forge
xorg-libxdmcp             1.1.5                h0e40799_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.5                ha9f60a1_7    conda-forge
zipp                      3.23.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.23.0          py313ha7868ed_2    conda-forge
zstd                      1.5.7                hbeecb71_2    conda-forge
