[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ksbcw"
version = "0.1.0"
dependencies = [
    "numpy==2.3.0",
    "scipy==1.15.2",
    "matplotlib==3.10.3",
    "ipython==9.3.0",
    "jupyterlab==4.4.3",
    "pandas==2.3.0",
    "geopy==2.4.1"
]
